amanasia/urls.py
from django.contrib import admin
from django.urls import path
from accounts import views

urlpatterns = [
    path('', views.home_redirect, name='redirect'),
    path('home', views.EntryListView.as_view(), name='home'),
    path('<int:pk>', views.EntryDetailView.as_view(), name='Entries_detail'),
    path('create', views.EntryCreateView.as_view(), name='Entries_create'),
    path('update/<int:pk>', views.EntryUpdateView.as_view(), name='Entries_update'),
    path('delete/<int:pk>', views.EntryDeleteView.as_view(), name='Entries_delete'),
    path('excel/', views.data_to_excel, name='excel'),
    path('admin', admin.site.urls),
]

accounts/models.py
from django.db import models
from datetime import date

# Create your models here.
class Entries(models.Model):
    purchaser_name = models.CharField(max_length=30)
    purchaser_address = models.TextField()
    gstin_no = models.IntegerField()
    description = models.CharField(max_length=25)
    hsn_code = models.IntegerField()
    quantity = models.IntegerField()
    rate = models.IntegerField()
    taxable_value = models.IntegerField()
    packaging = models.IntegerField()
    total_amount_before_tax = models.IntegerField()
    cgst = models.IntegerField()
    sgst = models.IntegerField()
    total_amount_after_tax = models.IntegerField()
    date = models.DateField(("Date"), auto_now_add=True)

accounts/views.py
from django.shortcuts import render , HttpResponseRedirect
from .models import Entries
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from excel_response import ExcelResponse

# Create your views here.


def home_redirect(request):
    return HttpResponseRedirect(reverse('home'))

def data_to_excel(request):
    data = Entries.objects.all()
    return ExcelResponse(data, output_filename='Accounts Data')


class EntryListView(ListView):
    model = Entries
    template_name = 'accounts/home.html'
    ordering = ['-id']


class EntryDetailView(DetailView):
    model = Entries



class EntryCreateView(CreateView):
    model = Entries
    fields = ['purchaser_name',
                'purchaser_address',
                'gstin_no',
                'description',
                'hsn_code',
                'quantity',
                'rate',
                'taxable_value',
                'packaging',
                'total_amount_before_tax',
                'cgst',
                'sgst',
                'total_amount_after_tax',]
    success_url = reverse_lazy('redirect')


class EntryUpdateView(UpdateView):
    model = Entries
    fields = ['purchaser_name',
              'purchaser_address',
              'gstin_no',
              'description',
              'hsn_code',
              'quantity',
              'rate',
              'taxable_value',
              'packaging',
              'total_amount_before_tax',
              'cgst',
              'sgst',
              'total_amount_after_tax',]
    success_url = reverse_lazy('redirect')


class EntryDeleteView(DeleteView):
    model = Entries
    success_url = reverse_lazy('redirect')

accounts/templates/accounts/Entries_confirm_delete.html
{% extends 'accounts/base.html' %}
{% load static %}

{% block home %}
    <div class="delete-container">
        <form  method="post" class="delete-box">
            {% csrf_token %}
            <h1>Are you sure?</h1>
            <input  type="submit"  value="Yes">
        </form>
        <button onclick="goBack()"><img src="{% static 'accounts/back.svg' %}" alt="back"></button>
    </div>
{% endblock %}

accounts/templates/accounts/Entries_detail.html
{% extends 'accounts/base.html' %}
{% load static %}

{% block home %}
    <div class="entries-form">
        <div><h2>Purchaser Name</h2>{{ object.purchaser_name }}</div>
        <div><h2>Purchaser Address</h2>{{ object.purchaser_address }}</div>
        <div><h2>GSTIN no.</h2>{{ object.gstin_no }}</div>
        <div><h2>Description</h2>{{ object.description }}</div>
        <div><h2>HSN Code</h2>{{ object.hsn_code }}</div>
        <div><h2>Quantity</h2>{{ object.quantity }}</div>
        <div><h2>Rate</h2>{{ object.rate }}</div>
        <div><h2>Texable Value</h2>{{ object.taxable_value }}</div>
        <div><h2>Packaging</h2>{{ object.packaging }}</div>
        <div><h2>Total Amount Before Tax</h2>{{ object.total_amount_before_tax }}</div>
        <div><h2>CGST</h2>{{ object.cgst }}</div>
        <div><h2>SGST</h2>{{ object.sgst }}</div>
        <div><h2>Total Amount After Tax</h2>{{ object.total_amount_after_tax }}</div>
        <button onclick="goBack()"><img src="{% static 'accounts/back.svg' %}" alt="back"></button>
    </div>
    <div class="date">{{ object.date }}</div>
    <script>
        console.log('hello')
    </script>
{% endblock %}

accounts/templates/accounts/Entries_form.html
{% extends 'accounts/base.html' %}
{% load static %}

{% block home %}
    <form method="post" class="entries-form">
        {% csrf_token %}
        <div><label for="id_purchaser_name">Purchaser Name</label>{{ form.purchaser_name }}</div>
        <div><label for="id_purchaser_address">Purchaser Address</label>{{ form.purchaser_address }}</div>
        <div><label for="id_gstin_no">GSTIN no.</label>{{ form.gstin_no }}</div>
        <div><label for="id_description">Description</label>{{ form.description }}</div>
        <div><label for="id_hsn_code">HSN Code</label>{{ form.hsn_code }}</div>
        <div><label for="id_quantity">Quantity</label>{{ form.quantity }}</div>
        <div><label for="id_rate">Rate</label>{{ form.rate }}</div>
        <div><label for="id_taxable_value">Texable Value</label>{{ form.taxable_value }}</div>
        <div><label for="id_packaging">Packaging</label>{{ form.packaging }}</div>
        <div><label for="id_total_amount_before_tax">Total Amount Before Tax</label>{{ form.total_amount_before_tax }}</div>
        <div><label for="id_cgst">CGST</label>{{ form.cgst }}</div>
        <div><label for="id_sgst">SGST</label>{{ form.sgst }}</div>
        <div><label for="id_purchaser_name">Total Amount After Tax</label>{{ form.total_amount_after_tax }}</div>
        <input class="button" type="submit" value="Submit">
        <button onclick="goBack()"><img src="{% static 'accounts/back.svg' %}" alt=""></button>
    </form>
{% endblock %}

accounts/templates/accounts/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'accounts/style.css' %}">
    <title>Amanasia Accounts</title>
</head>
<body>
    {% block home %}
        <h1>Error</h1>
    {% endblock %}

    <script src="{% static 'accounts/push.js' %}"></script>
    <script>

        function goBack() {
            window.history.back()
        }

        let excel = document.querySelector('.excel-download')
        excel.addEventListener('click', () => {
            Push.create('File Downloaded!')
        })
    </script>
</body>
</html>

accounts/templates/accounts/home.html
{% extends 'accounts/base.html' %}
{% load static %}

{% block home %}

    <header>
        <h1>Amanasia Accounts</h1>
    </header>
    <nav>
        <a class="excel-download" href="{% url 'excel' %}">Download Excel</a>
        <a href="{% url 'Entries_create' %}">ADD</a>
    </nav>
    <div class="accounts-container">
        <div class="entry-list">
            <h2 class="list-heading">Purchaser Name</h2>
            <h2 class="list-heading">Quantity</h2>
            <h2 class="list-heading">Total Amount</h2>
        </div>
        {% for entry in object_list %}
            <div class="entry-list">
{#                <a href="{% url 'Entries_detail' entry.id %}" class="entry-list">#}
                <div class="list-item">
                    <h3>{{ entry.purchaser_name}}</h3>
                </div>
                <div class="list-item">
                    <h4>{{ entry.quantity }}</h4>
                </div>
                <div class="list-item">
                    <h4>{{ entry.total_amount_after_tax }}</h4>
                </div>
                <div>
                    <a href="{% url 'Entries_delete' entry.id %}" class="icon"><img src="{% static 'accounts/delete.svg' %}" alt=""></a>
                </div>
                <div>
                    <a href="{% url 'Entries_update' entry.id %}" class="icon"><img src="{% static 'accounts/edit.svg' %}" alt=""></a>
                </div>
                <div>
                    <a href="{% url 'Entries_detail' entry.id %}" class="icon"><img src="{% static 'accounts/info.svg' %}" alt=""></a>
                </div>
{#                </a>#}
            </div>
        {% endfor %}
    </div>

{% endblock %}